clc;clear;
imh = image(cat(3,cells,z,z)); 
set(imh, 'erasemode', 'none') 
axis equal 
axis tight

z = zeros(n); 
cells = z; 
cells(n/2,.25*n:.75*n) = 1; 
cells(.25*n:.75*n,n/2) = 1;

x = 2:n-1; 
y = 2:n-1; 
sum(x,y) = cells(x,y-1) + cells(x,y+1) + ... 
    cells(x-1, y) + cells(x+1,y) + ... 
    cells(x-1,y-1) + cells(x-1,y+1) + ... 
    cells(x+1,y-1) + cells(x+1,y+1); 
cells = (sum==3) | (sum==2 & cells);

%build the GUI 
%define the plot button 
plotbutton=uicontrol('style','pushbutton',...  
    'string','Run', ... 
    'fontsize',12, ... 
    'position',[100,400,50,20], ... 
    'callback', 'run=1;');

%define the stop button 
erasebutton=uicontrol('style','pushbutton',... 
    'string','Stop', ... 
    'fontsize',12, ... 
    'position',[200,400,50,20], ... 
    'callback','freeze=1;'); 

%define the Quit button 
quitbutton=uicontrol('style','pushbutton',... 
    'string','Quit', ... 
    'fontsize',12, ... 
    'position',[300,400,50,20], ... 
    'callback','stop=1;close;'); 

number = uicontrol('style','text', ... 
    'string','1', ... 
    'fontsize',12, ... 
    'position',[20,400,50,20]);

